### ISSUE TITLE
Customize location .npmrc

### ISSUE THREAD

**Issue by ccarretti777** [arkanjoms/nexus-npm#20]
Enable to work with Jenkins pulgin NodeJs (https://plugins.jenkins.io/nodejs/) for override .npmrc 
Currently the console jenkins in front of the following command piepline:

nodejs(nodeJSInstallationName: "${nodeinstallname}", configId: "${nodeconfigid}") {
        sh label: 'publishing-lib-ng...', script: "nexus-npm deploy"
    }

returns:

+ nexus-npm deploy
[default.js-debug]: 0.1.4
[default.js-debug]: Loading package.json
[default.js-debug]: Loading ~/.npmrc
[default.js-error]: ENOENT: no such file or directory, open '/var/lib/jenkins/.npmrc'

**Comment by arkanjoms** [comment]
Released version 0.2.0
