### ISSUE TITLE
publish-snapshot.js DATE Issue

### ISSUE THREAD

**Issue by StancuFlorin** [arkanjoms/nexus-npm#3]
There is an issue here

var now = moment().format('YYYYDDMM.hhmmss');
appConfig.packageJson.version = appConfig.packageJson.version + "." + now;
fs.writeFileSync('package.json', JSON.stringify(appConfig.packageJson, null, 2));

more exactly on the date format. Is taken the day first and then the month. This is an issue because 

20172407 is bigger then 20171808, but the last version was pushed last.

**Comment by arkanjoms** [comment]
Resolved in version 0.0.6
